# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEVdASaf8ttJrOj7w1cH4Sx8habTT4Nx
"""

import torch
from diffusers import StableDiffusionPipeline
from peft import PeftModel

model_id = "runwayml/stable-diffusion-v1-5"
lora_path = "path_to_your_lora_weights"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    safety_checker=None
).to("cuda")

pipe.unet = PeftModel.from_pretrained(pipe.unet, lora_path)

prompt = "A realistic photo of an American car"
image = pipe(prompt).images[0]
image.save("generated_image.png")

print("Image generated successfully.")