# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEVdASaf8ttJrOj7w1cH4Sx8habTT4Nx
"""

import torch
from diffusers import UNet2DConditionModel
from transformers import CLIPTextModel
from peft import LoraConfig, get_peft_model

model_id = "runwayml/stable-diffusion-v1-5"

# Load base UNet
unet = UNet2DConditionModel.from_pretrained(model_id, subfolder="unet")

# Freeze base model
unet.requires_grad_(False)

# Add LoRA configuration
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["to_k", "to_q", "to_v", "to_out.0"],
    lora_dropout=0.05,
    bias="none"
)

unet = get_peft_model(unet, lora_config)

print("LoRA successfully applied to UNet.")